version = 1

exclude_patterns = [
  "e2e",
  ".vscode"
]

[[analyzers]]
name = "test-coverage"

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  environment = [
    "nodejs",
    "jest",
    "mongo"
  ]