# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build oxide-commerce`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t oxide-commerce`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system oxide-commerce && \
          adduser --system -G oxide-commerce oxide-commerce

COPY dist/oxide-commerce oxide-commerce
RUN chown -R oxide-commerce:oxide-commerce .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix oxide-commerce --omit=dev -f install

CMD [ "node", "oxide-commerce" ]
